### ISSUE TITLE
Narrow time-machine to one resource

### ISSUE THREAD

**Issue by korjavin** [kubevious/kubevious#54]
Use case:
There are thousand resources, but I am looking when and how was changes a specific  config map

**Comment by rubenhak** [comment]
hi @korjavin, this is definitely very useful. This was added to Kubevious SaaS. Because of differences in the way storage layer is implemented in SaaS vs open-source this capability is not easily portable. 

For the time being I'd recommend trying it out with Kubevious SaaS, which is currently free, until we get bit more bandwidth and implement it for open-source. Here is an article and walkthrough about this: [https://kubevious.io/blog/post/kubernetes-gremlins-what-broke-my-cluster](https://kubevious.io/blog/post/kubernetes-gremlins-what-broke-my-cluster)

**Comment by kubevious** [comment]
@korjavin, we have released the new Kubevious open-source version and the Change History capability is now ported to the open-source project. A quick how it works below (sorry for the poor gif quality, GitHub significantly reduces the image size):

![CleanShot 2022-05-04 at 17 42 43](https://user-images.githubusercontent.com/59004473/166848914-00d46f78-8b5e-4e9b-b06b-fa58adf66dae.gif)

Please try installing again using the latest chart and let us know how it works for you.

```sh
kubectl create namespace kubevious

helm repo add kubevious https://helm.kubevious.io

helm repo update

helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.9.27 -n kubevious
```
For more details on installation options, visit [Deployment Repository](https://github.com/kubevious/helm).
