### ISSUE TITLE
Manifests generated by the Helm chart don't contain metadata.namespace even though it's specified

### ISSUE THREAD

**Issue by robertomlsoares** [kubevious/kubevious#80]
### Describe the bug
I'm trying to install kubevious in a cluster using `helm template`. The reason we use `template` instead of `upgrade` (or other imperative Helm commands) is that we use a GitOps solution to deploy the manifests to the cluster.

So first, we use `helm template` to generate the manifests, then push them to a git repository, and those will then be applied to the cluster. However, Kubevious doesn't seem to set the `metadata.namespace` on the manifests generated by Helm even though that parameter is specified.

### To Reproduce

1. Run the following command:
```bash
helm template kubevious \
  --repo https://helm.kubevious.io \
  --release-name kubevious \
  --namespace kubevious \
  --version 1.1.1 \
> kubevious.yaml
```

2. Verify that none of the manifests have `metadata.namespace`.

### Expected behavior
`metadata.namespace` to be set to the value specified at `--namespace kubevious`.

### Environment Details:
 - Cluster: v1.22.12-gke.500
 - Helm CLI version: v3.10.0

**Comment by tanmay-bhat** [comment]
Hey @robertomlsoares  thanks for reporting the issue.

@rubenhak  I can see that the resource definition doesn't contain namespace defined in templates. For example the backend [deployment](https://github.com/kubevious/helm/blob/master/kubernetes/templates/backend/deployment.yaml).


This can be easily fixed by adding `namespace: {{ .Release.Namespace }}` to the template manifests.

What's your thought on this, let's add it ?

**Comment by rubenhak** [comment]
@robertomlsoares, @tanmay-bhat, that's a reasonable ask. Could you try this out with the new version?
```sh
$ helm repo add kubevious https://helm.kubevious.io
$ helm template kubevious/kubevious \
  --namespace kubevious \
  --version 1.1.2
```

**Comment by robertomlsoares** [comment]
Works perfectly, thanks for the quick turnaround!

**Comment by rubenhak** [comment]
Sounds great. I'll then close this issue.
